# Generated by Django 6.0.6 on 2026-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_privacypolicypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='TestimonialsPage',
        ),
    ]
