# Generated by Django 6.0.6 on 2026-08-15 11:53
# Manually adjusted: ALL operations in this migration are wrapped in
# SeparateDatabaseAndState with empty database_operations. Heroku's production
# database already has both the TestimonialsPage/Testimonial cleanup (applied
# under pages.0007) and the about_image column on pages_aboutpage (applied
# under an earlier, differently-numbered migration on that environment).
# This migration now only updates Django's migration-state bookkeeping to
# match local history — it issues no SQL at all.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_testimonialspage_page_ptr_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='testimonialspage',
                    name='page_ptr',
                ),
                migrations.AddField(
                    model_name='aboutpage',
                    name='about_image',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
                ),
                migrations.DeleteModel(
                    name='Testimonial',
                ),
                migrations.DeleteModel(
                    name='TestimonialsPage',
                ),
            ],
            database_operations=[],
        ),
    ]