# Generated by Django 6.0.6 on 2026-08-15 11:53
# Manually adjusted: the TestimonialsPage/Testimonial removal operations are
# wrapped in SeparateDatabaseAndState because that cleanup was already applied
# to the production database under a different migration (pages.0007). Only
# the database state bookkeeping needs to catch up here — no SQL should run
# for those operations. The AddField for about_image is untouched and still
# runs for real, since nothing else has created that field yet.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_testimonialspage_page_ptr_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='testimonialspage',
                    name='page_ptr',
                ),
                migrations.DeleteModel(
                    name='Testimonial',
                ),
                migrations.DeleteModel(
                    name='TestimonialsPage',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]