# Generated by Django 6.0.6 on 2026-07-06 13:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWorkIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Latest Work Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LatestWorkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('category', models.CharField(choices=[('wifi', 'Wi-Fi'), ('smart_home', 'Smart Home'), ('cctv', 'CCTV'), ('broadband', 'Home Broadband'), ('training', 'Training'), ('networking', 'Home Networking'), ('other', 'Other')], default='other', max_length=50)),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Latest Work Post',
            },
            bases=('wagtailcore.page',),
        ),
    ]
