# Generated by Django 6.0.6 on 2026-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestworkpage',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
